spring.application.name=edu

spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.pphibwmmzaljfdibkpyw
spring.datasource.password=EtTlz4jhsRAgWURb
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origin=http://localhost:5173